// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = "https://vciobtmysjxmljupfytw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaW9idG15c2p4bWxqdXBmeXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDM5NzMsImV4cCI6MjA3MTc3OTk3M30.hpGr3S8docfaBzvOgrjlOXJ-KbHmpC0czQWlJRhauVE";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
